import type { Metadata } from "next";
import StyledJsxRegistry from "@/app/registry";
import "@/app/globals.css";

import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <StyledJsxRegistry>
        <body>{children}</body>
      </StyledJsxRegistry>
    </html>
  );
}
